### ISSUE TITLE
engine/rest: market names between exchanges are very inconsistent

### ISSUE THREAD

**Issue by tryphe** [tryphe/trader#1]
Trying to differentiate between market names on different exchanges sucks. Need to combine them. Formatting is:

Poloniex: `BASE_QUOTE`
Bittrex: `BASE-QUOTE`
Binance: `QUOTEBASE`

Maybe I'll just convert everything to do `BASE_QUOTE`. ~The other option would be to split it into 2 strings, which changes more stuff, so prefer not to do it this way.~ Update: We want to support the concept of base currency and quote currency separately now, because of the way spruce strat takes currency names and applies them to the base.

**Comment by tryphe** [comment]
Update: accepted formats for input are `BASE-QUOTE` and `BASE_QUOTE` for all exchanges. "Fixed" (this is just a refactor for later code) in https://github.com/tryphe/trader/commit/ab3e8f87a7b8524e35044ebc32bebd85c50e3486 https://github.com/tryphe/trader/commit/0500676427480747baa3090bd784928ec503adfd https://github.com/tryphe/trader/commit/2fa64e3eadbdb9875cf97193726c292db15c263e https://github.com/tryphe/trader/commit/cffa65c6dcc1df3de2470b523a69f8b0031576ee https://github.com/tryphe/trader/commit/706fb4f677a2403e3f142f52a7c559d745be3ae1 https://github.com/tryphe/trader/commit/3f97a9c28f7595de29739ab4e2d7e40d91293cb7 https://github.com/tryphe/trader/commit/cad9a45a8e6c6aba9e90d8fe06c85a34d356f29b

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
wonderluster, @bchaichon, @emergerrrd, @Wangzhijie2016, @wufeiafei, @phxc, @wuliwong, @kurtc2008, @theshdf, @clarkeadg, @toby20130333, @cageyz, @doraemon93, @takeshi-1000, @mzonghao, @moubuns, @Samuel-Guo, @zhoudaqing, @assqingt, @f13end, @vestlavie, @Ag0n1fy, @toannhu96, @yagiz, @TKUsu, @martindelia, @leitdeux, @20cmdingding, @mdcs96, @Leverse, @lingwei0604, @kenpingliu, @Shinthantaung25, @albertogalan, @whitespur, @oguzhankiyar, @CGNHACKER, @cyberpunka, @luo1994, @junejan143, @sbalbinot, @j1v, @jaabari, @HarveyWolfstein, @weilii, @Mdk2022, @Starlight143, @guilhrmefp, @vipycm, @sylvat

**Comment by ozancrk** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
LEECHHE, @jboxxx, @canlau, @Saruultugs, @JacobAlvarezSE, @shamabe, @xlciela, @lanesket, @wpank, @markcheno, @kiennt23, @IEdison, @rcallaby, @snstgithub, @pkliang, @peng1027, @joelquek, @overtrue, @pnpn521521, @arkii, @tangivis, @okarakose, @irhallac, @EMichaelC, @glyphx, @LeviathanJGG, @andresilvasantos, @weisnc, @marzwu, @xiaozhun, @ryomak, @Jimexist, @calvinjiang, @iCodyYang, @Stef3478, @waifwaif, @upost, @trurebel, @hytest, @JustBbing, @sonpython, @emregulcan, @Kindly12, @AppServiceProvider, @neoKushan, @akgnah, @grezbo, @fermicat, @klpanda, @omerg

**Comment by LeviathanJGG** [comment]
已经受到你的邮件，请等待我的回复，谢谢，祝你生活愉快，工作顺利！
